# send build notifications to the #mapcache IRC channel
# homepage: https://github.com/marketplace/actions/notify-irc

name: "IRC Push Notification"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  irc_notify:
    runs-on: ubuntu-latest
    #if: github.repository == 'MapServer/mapcache'
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v2
        if: github.event_name == 'push'
        with:
          channel: "#mapcache"
          server: "irc.libera.chat"
          nickname: mapcache-github-notifier
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v2
        if: github.event_name == 'pull_request'
        with:
          channel: "#mapcache"
          server: "irc.libera.chat"
          nickname: mapcache-github-notifier
          message: |
            ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v2
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#mapcache"
          server: "irc.libera.chat"
          nickname: mapcache-github-notifier
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
